version: '3'
services:
  
  ##############
  # DELUGE-VPN #
  ##############

  deluge:
    container_name: deluge
    image: binhex/arch-delugevpn
    ports:
      - "<YOUR LOCAL IP>:8112:8112"
      - "<YOUR LOCAL IP>:8118:8118"
      - "<YOUR LOCAL IP>:58846:58846"
      - "<YOUR LOCAL IP>:58946:58946"
    volumes:
      - ./config/deluge:/config
      - ~/Downloads:/Downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      VPN_ENABLED: yes
      VPN_USER: <YOUR NORDVPN VPN_USERNAME>
      VPN_PASS: <YOUR NORDVPN VPN_PASSWORD>
      VPN_PROV: nordvpn
      VPN_OPTIONS: 
      STRICT_PORT_FORWARD: yes
      ENABLE_PRIVOXY: yes
      LAN_NETWORK: 10.0.0.0/0
      NAME_SERVERS: 1.1.1.1, 1.0.0.1
      DELUGE_DAEMON_LOG_LEVEL: info
      DELUGE_WEB_LOG_LEVEL: info
      ADDITIONAL_PORTS: 1234
      DEBUG: false
      UMASK: 000
      PUID: 1000
      PGID: 1000   
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  
  ##########
  # RADARR #
  ##########
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - ./config/radarr:/config
      - <PATH TO SAVE YOUR MEDIA FILES>:<PATH TO SAVE YOUR MEDIA FILES>
      - ~/Downloads:/Downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    expose:
      - 7878

  ##########
  # SONARR #
  ##########
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - ./config/sonarr:/config
      - <PATH TO SAVE YOUR MEDIA FILES>:<PATH TO SAVE YOUR MEDIA FILES>
      - ~/Downloads:/Downloads
    ports:
      - 8989:8989
    restart: unless-stopped    
    expose:
      - 8989

  ###########
  # JACKETT #
  ###########
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true #optional
    volumes:
      - ./config/jackett:/config
      - ~/Downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped    
    expose:
      - 9117

  #############
  # PORTAINER #
  #############
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
    expose:
      - 9000

  ###########
  # HAPROXY #
  ###########
  haproxy:
    image: haproxy:2.3
    container_name: haproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
    restart: always
    expose:
      - 80
      - 443
  ###############
  # DDNS UPDATE #
  ###############
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    environment:
      - API_KEY=<YOUR CLOUDFLARE API KEY>
      - ZONE=<YOUR DOMAIN>
      - PROXIED=true